### ISSUE TITLE
the cycle data of the period 

### ISSUE THREAD

**Issue by zzy7758565** [ServiceNow/stl-decomp-4j#12]
When the original data contains anomalous points, the cycle data of the period where the abnormal data is also changed. However, the stl function of R language does not produce this phenomenon, but keeps the previous characteristic，How to use robust features?

**Comment by jcrotinger** [comment]
Can you provide an example? The decomposition is non-robust by default, as is the R interface. When robustness iterations are chosen, then outliers are measured by the size of the residual and their impact on the smoothing is weighted with smaller weights, so very far outliers should be ignored if there is sufficient data (meaning sufficient cycles).

The options on `SeasonalTrendLoess.Builder` try to follow those of the R interface. You can just call `setRobust()` or you can choose the inner and outer iterations with `setInnerIterations` and `setRobustnessIterations`. The `setRobust` call does:

		/**
		 * Set the default robust STL iteration counts (15 robustness iterations, 1 inner iteration).
		 *
		 * @return this
		 */
		public Builder setRobust() {
			fInnerIterations = 1;
			fRobustIterations = 15;
			return this;
		}
