### ISSUE TITLE
Not Issue more a clarification

### ISSUE THREAD

**Issue by inneractive-opensrc** [ServiceNow/stl-decomp-4j#2]
Hi

I'm trying to use your package to replace some R code so I'm trying to get same result as stl with R implementation. Now the parameters are very different between your implementation and R. 
I call the R like this 
stl( ts(data[[2L]], frequency = 1440), s.window = "periodic", robust = TRUE)

Now I set the frequency as 1440 because my time series have distribution on minutes.
Start Date : 1980-09-25 14:01:00
End Date: 1980-10-05 13:58:00

I can't figure out what are the settings for PeriodLength and SeasonalWidth or do I need to change something else 

I've also tried the package stl-java from brandtg there was here some difference with R but not big as I get with your implementation.

Thanks fro your help

**Comment by inneractive-opensrc** [comment]
After setting the degree to 0 miracle all it's equal

**Comment by jcrotinger** [comment]
The R "periodic" setting is equivalent to setting the degree of the seasonal loess smoother to 0 and setting the width of the smoother to be essentially infinite. When this is done, the individual cyclic sub-series just get averaged, resulting in a perfectly periodic series. There are some unit tests that check this but they set it up manually. There are a couple of utility functions in SeasonalTrendLoess: performPeriodicDecomposition and performRobustPeriodicDecomposition that will run a version of this but they don't expose the full functionality and are mainly used by me for quick checks. I have a TODO to add a setPeriodic() function to the Builder but have not gotten around to it yet. Should be straightforward. Right now I just want to get the travis-ci build pushing to a maven repo, which has taken the spare cycles I've had to work on this.

**Comment by jcrotinger** [comment]
I added `SeasonalTrendLoess.Builder.setPeriodic()` for the 1.0.0 release, which ...<drumroll>... is now available in a central maven repo near you. :)
