### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by lmxhappy** [ServiceNow/stl-decomp-4j#7]
in stl-decomp-4j directory mvn install and get error as following.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project stl-decomp-4j: Exit code: 127 -> [Help 1]
[ERROR]

**Comment by shayanlinux** [comment]
You can skip the maven-gpg-plugin by `mvn clean install -Dgpg.skip=true`

**Comment by lmxhappy** [comment]
thanks.  had better update the readme.

**Comment by lmxhappy** [comment]
After that, compile the example StlDemoRestServer and get error

[ERROR] Failed to execute goal on project StlDemoRestServer: Could not resolve dependencies for project com.github.servicenow.stl4j:StlDemoRestServer:jar:1.0-SNAPSHOT: Failure to find com.github.servicenow.stl4j:stl-decomp-4j:jar:1.0-SNAPSHOT in http://mvnrepo.alibaba-inc.com/mvn/repository was cached in the local repository, resolution will not be reattempted until the update interval of tbmirror-all has elapsed or updates are forced -> [Help 1]

**Comment by shayanlinux** [comment]
The problem with the StlDemoRestServer dependency on stl-decomp-4j is also solved, please pull and rebuild.

**Comment by shayanlinux** [comment]
@jcrotinger should we comment out maven-gpg-plugin?

**Comment by jcrotinger** [comment]
Is that used by travis? Or only for local builds? It certainly isn't necessary for local builds and may be an artifact of Cong and my first attempt to get builds distributed.

**Comment by jcrotinger** [comment]
I moved the master versions all to 1.0.3-SNAPSHOT. I hadn't been cleaning out my .m2 cache so these weren't failing for me - my bad!

**Comment by jcrotinger** [comment]
With the update to the README (thanks @lmxhappy) and the fixes to the various dependency versions on the poms, I'm going to close this. If the gpg isn't needed for travis (I think travis is doing that separately but need to confirm), we can remove that section later and change the README back.
